# Generated by Django 5.2.1 on 2025-06-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_studentmodel_email_alter_studentmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='roll',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
