# Generated by Django 5.2.1 on 2025-06-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_studentmodel_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='course',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='marks',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
