# Generated by Django 5.2.1 on 2025-06-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_studentmodel_course_studentmodel_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='course',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='marks',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='roll',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
