# Generated by Django 5.2.1 on 2025-07-31 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
